# Site Settings

title       : My Secret Lair

# Google Analytics Property ID
# ganalytics  : UA-00000000-0

# Menu Include
# menu:
#   - name    : about
#     path    : /about.html
#   - name    : projects
#     path    : /projects.html
#   - name    : blog
#     path    : /

# Jekyll Configuration

source      : source
destination : public
plugins		: source/_plugins

# Jekyll-Lair Configuration

